local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("AuraAlarm", "enUS", true)
if not L then return end

L["Add and remove auras"] = true
L["Duration"] = true
L["Set the flash duration"] = true
L["<Duration here>"] = true
L["Color"] = true
L["Change the flash color"] = true
L["Aura Name"] = true
L["<Aura name here>"] = true
L["Name for Aura"] = true
L["Remove"] = true
L["Remove aura"] = true
L["Add Aura"] = true
L["Add a aura"] = true
L["You are afflicted by %s."] = true
L["Warning Sound"] = true
L["Sound to play"] = true
L["Play Sound"] = true
L["Toggle playing sounds"] = true
L["Mode"] = true
L["Alarm mode"] = true
L["Flash Once"] = true -- this used to be "Flash Background"
L["Persist"] = true
L["None"] = true
L["Aura removed."] = true
L["%s added."] = true
L["%s added to AuraAlarm."] = true
L["<New aura here>"] = true
L["Captured Auras - Click to add"] = true
L["Enable Mouse"] = true
L["Unit"] = true
L["Stacks"] = true
L["Frame x position"] = true
L["Frame y position"] = true
L["Stacks: "] = true
L["Harmful"] = true
L["Helpful"] = true
L["Type"] = true
L["Normal"] = true
L["Determined"] = true
L["Support Mode"] = true
L["Use 'Determined' for events that don't show up in the combat log."] = true
L["Show Icon"] = true
L["Show icon frame"] = true
L["Determined Mode Rate (in ms)"] = true
L[" (D)"] = true -- Some short tag meaning "Debuff"
L["Blink"] = true
L["Blink Rate"] = true
L["0 means do not consider stack count."] = true
L["Persisting Sound"] = true
L["Toggle repeating sound throughout aura. This only pertains to Persist Mode."] = true
L["Sound Rate"] = true
L["Rate at which Persisting Sound will fire. This is in milliseconds."] = true
L["Layers"] = true
L["Layer"] = true
L["This alarm's layer"] = true
L["How many screen layers"] = true
L["Color key"] = true
L["Usually a black color with half opacity."] = true
L["Fade Time"] = true
L["Duration of fade 'in' and 'out' effects."] = true
L["Reset AuraAlarm"] = true
L["Sets"] = true
L["Click this in case the icon or background doesn't fade. May fix other issues as well."] = true
L["Garbage Collect"] = true
L["Whether to collect garbage."] = true
L["Garbage Collection Rate"] = true
L["Rate at which garbage collection will be done (in ms)"] = true
L["Enabled"] = true
L["Whether this alarm is enabled"] = true
L["Default"] = true
L["Current Set"] = true
L["Which alarm set to use"] = true
L["Save Set"] = true
L["Delete Set"] = true
L["Create a Set"] = true
L["Delete Set"] = true
L["Settings"] = true
L["Configure AuraAlarm"] = true
L["Coordinates"] = true
L["Frames"] = true
L["Memory"] = true
L["Troubleshooting"] = true
L["Toggle enabled off or on for each alarm. Enter a name for this set."] = true
L["Set saved."] = true

