local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("AuraAlarm", "enUS", true)
if not L then return end

L["Add and remove auras"] = true
L["Duration"] = true
L["Set the flash duration"] = true
L["<Duration here>"] = true
L["Color"] = true
L["Change the flash color"] = true
L["Aura Name"] = true
L["<Aura name here>"] = true
L["Name for Aura"] = true
L["Remove"] = true
L["Remove aura"] = true
L["Add Aura"] = true
L["Add a aura"] = true
L["You are afflicted by %s."] = true
L["Warning Sound"] = true
L["Sound to play"] = true
L["Play Sound"] = true
L["Toggle playing sounds"] = true
L["Mode"] = true
L["Alarm mode"] = true
L["Flash Background"] = true
L["Persist"] = true
L["None"] = true
L["Aura removed."] = true
L["%s added."] = true
L["%s added to AuraAlarm."] = true
L["<New aura here>"] = true
L["Captured Auras - Click to add"] = true
L["Enable Mouse"] = true
L["Unit"] = true
L["Stacks"] = true
L["Frame x position"] = true
L["Frame y position"] = true
L["Stacks: "] = true
L["Harmful"] = true
L["Helpful"] = true
L["Type"] = true
L["Normal"] = true
L["Determined"] = true
L["Support Mode"] = true
L["Select between determined and normal mode. Use 'Determined' for events that don't show up in the combat log."] = true
L["Show Icon"] = true
L["Show icon frame"] = true
